baseurl = "/"
title = "Homepage"
DefaultContentLanguage = "en"

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
  [languages.ko]
    languageName = "Korean"
    languageCode = "ko-KR"