baseurl = "/"
title = "Homepage"
DefaultContentLanguage = "en"

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
  [languages.ko]
    languageName = "Korean"
    languageCode = "ko-KR"



[menu]

  [[menu.main]]
    url = "/products"
    name = "Products"
    weight = 1
  [[menu.main]]
    url = "/values"
    name = "Values"
    weight = 2
    pre = "<i class='fa fa-heart'></i>"
  [[menu.main]]
    url = "/post"
    name = "Post"
    weight = 3
  [[menu.main]]
    url = "/contact"
    name = "Contact"
    weight = 4
