baseURL: /
title: KUMC Albuquerque
DefaultContentLanguage: ko
hasCJKLanguage: true
PaginatePath: "p"
disableKinds:
- taxonomy
- taxonomyTerm
googleAnalytics: UA-140715412-1

languages:
  en:
    languageName: English
    languageCode: en-US
    dateFormat: 1/2/2006
    menu:
      main:
        - url: /about
          name: About
          weight: 3
        # - url: /worship
        #   name: Worship
        #   weight: 1
        - url: /education
          name: Education
          weight: 2
        - url: /contact
          name: Contact
          weight: 4
  ko:
    languageName: 한국어
    languageCode: ko-KR
    dateFormat: 2006/01/02
    menu:
      main:
        - url: /about
          name: 교회소개
          weight: 1
        # - url: /worship
        #   name: 말씀과찬양
        #   weight: 1
        - url: /education
          name: 교회학교
          weight: 2
        - url: /contact
          name: Contact
          weight: 4
